services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TMDB_API_KEY: ${TMDB_API_KEY}
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_TMDB_IMAGE_BASE_URL: ${NEXT_PUBLIC_TMDB_IMAGE_BASE_URL}
      NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    env_file:
      - .env
